LuandryCustomerApp/Controllers/ListViewComponentsController.cs
using LuandryCustomerApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LuandryCustomerApp.Controllers
{
    public class ListViewComponentsController : Controller
    {
        [ChildActionOnly]
        public PartialViewResult RenderPaging(PagingViewModel pagingViewModel)
        {
            int pageNumber = pagingViewModel.PageNumber,
                startPage = 1,
                endPage = pagingViewModel.TotalPages;

            if (pageNumber <= (startPage + 2) && endPage > 4)
            {
                endPage = startPage + 4;
            }
            else if (pageNumber >= (endPage - 2) && startPage < (endPage - 4))
            {
                startPage = endPage - 4;
            }
            else if ((pageNumber - startPage) > 2 && (endPage - pageNumber) > 2)
            {
                startPage = pageNumber - 2;
                endPage = pageNumber + 2;
            }

            pagingViewModel.StartPage = startPage;
            pagingViewModel.EndPage = endPage;
            return PartialView("ListViewComponents/_Paging", pagingViewModel);
        }
    }
}

LuandryCustomerApp/Controllers/PlacedOrdersController.cs
using LuandryCustomerApp.Infrastructure;
using LuandryCustomerApp.Models;
using LuandryCustomerApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace LuandryCustomerApp.Controllers
{
    public class PlacedOrdersController : Controller
    {
        private ModelMapping modelMapping = new ModelMapping();
        private lddsDBEntities dbContext = new lddsDBEntities();
        //private AppDbContext dbContext = new AppDbContext();
        // GET: PlacedOrders
        public ActionResult Index(string sortField = "id_asc", int pageNumber = 1, int pageSize = 10)
        {
            IQueryable<placed_orders> query0 = dbContext.placed_orders;

            var query = query0.Select(x => new PlacedOrderListViewModel()
            {
                id = x.id,
                created_at = x.created_at,
                updated_at = x.updated_at,
                deleted_at = x.deleted_at,
                store_id = x.store_id,
                time_placed = x.time_placed,
                detail = x.detail,
                order_status_id = (OrderStatus)x.order_status_id,
                customer_id = x.customer_id,
                capacity = x.capacity,
                estimated_capacity = x.estimated_capacity,
                delivery_address = x.delivery_address,
                delivery_latitude = x.delivery_latitude,
                delivery_longitude = x.delivery_longitude,
                service_total_price = x.service_total_price,
                priority = x.priority,
                review_id = x.review_id
            });

            int totalPages = (int)Math.Ceiling((decimal)query.Count() / pageSize);

            query = query.OrderBySortField(sortField);
            query = query.Skip((pageNumber - 1) * pageSize).Take(pageSize);

            ViewBag.TotalPages = totalPages;
            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            return View(query.ToList());
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            try
            {
                if (!id.HasValue) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                placed_orders placedOrder = dbContext.placed_orders.Find(id);
                if (placedOrder == null) return new HttpStatusCodeResult(HttpStatusCode.NotFound, $"placed_orders {id} is not found.");

                dbContext.placed_orders.Remove(placedOrder);
                dbContext.SaveChanges();

                if (Request.IsAjaxRequest())
                {
                    return new HttpStatusCodeResult(HttpStatusCode.OK, "Delete Success!");
                }
                else
                {
                    return RedirectToAction("Index", "PlacedOrders", new RouteValueDictionary(
                        this.ParseQueryString(Request.Form["RouteValues"] as string, this.CalculatePageNumber)));
                }
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }


        [HttpGet]
        [ActionName("Create")]
        public ActionResult CreateByGet()
        {
            ViewBag.CustomerData = GetCustomerData();
            ViewBag.StoreData = GetStoreData();
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult CreateByPost(PlacedOrderModifyViewModel viewModel)
        {
            
            if (ModelState.IsValid)
            {
                placed_orders placedOrder = modelMapping.CreatePlacedOrderModel(viewModel);
                dbContext.placed_orders.Add(placedOrder);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerData = GetCustomerData();
            ViewBag.StoreData = GetStoreData();
            return View(viewModel);
        }

        [HttpGet]
        [ActionName("Edit")]
        public ActionResult EditByGet(int? id)
        {
            if (!id.HasValue) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            placed_orders placedOrder = dbContext.placed_orders.Find(id);
            if (placedOrder == null) return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            PlacedOrderModifyViewModel viewModel = modelMapping.CreatePlacedOrderModifyModel(placedOrder);
            ViewBag.CustomerData = GetCustomerData();
            ViewBag.StoreData = GetStoreData();
            return View(viewModel);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditByPost(int? id)
        {
            if (!id.HasValue) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            placed_orders placedOrder = dbContext.placed_orders.Find(id);
            if (placedOrder == null) return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            PlacedOrderModifyViewModel viewModel = new PlacedOrderModifyViewModel();

            TryUpdateModel(viewModel);
            if (ModelState.IsValid)
            {
                modelMapping.UpdatePlacedOrderModel(viewModel, placedOrder);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerData = GetCustomerData();
            ViewBag.StoreData = GetStoreData();
            return View(viewModel);
        }

        private List<SelectListItem> GetCustomerData()
        {
            return dbContext.customers.Select(x => new SelectListItem()
            {
                Text = x.name,
                Value = x.id.ToString()
            }).ToList();
        }

        private List<SelectListItem> GetStoreData()
        {
            return dbContext.stores.Select(x => new SelectListItem()
            {
                Text = x.name,
                Value = x.id.ToString()
            }).ToList();
        }

       



        public ActionResult Test()
        {
            return View();
        }
    }
}

LuandryCustomerApp/Views/PlacedOrders/Create.cshtml
@model PlacedOrderModifyViewModel
@{
    ViewBag.Title = "Create";
}

<style>
    .field-validation-error {
        color: red;
    }

    .field-validation-error {
        border-color: red;
    }
</style>
@using (Html.BeginForm("Create", "PlacedOrders", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <table>
        <tr>
            <td>@Html.DisplayNameFor(m => m.store_id)</td>
            <td>
                @Html.DropDownListFor(m => m.store_id, ViewBag.StoreData as List<SelectListItem>, "Select Store", null)
            </td>
            <td>@Html.ValidationMessageFor(m => m.store_id)</td>
        </tr>

        <tr>
            <td>@Html.DisplayNameFor(m => m.time_placed)</td>
            <td>
                @Html.TextBoxFor(m => m.time_placed)
            </td>
            <td>@Html.ValidationMessageFor(m => m.time_placed)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.detail)</td>
            <td>
                @Html.TextBoxFor(m => m.detail)
            </td>
            <td>@Html.ValidationMessageFor(m => m.detail)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.order_status_id)</td>
            <td>
                @{ bool isChecked = true; }
                @foreach (var item in (int[])Enum.GetValues(typeof(OrderStatus)))
                {
                    @Html.RadioButtonFor(m => m.order_status_id, item, isChecked ? new { @checked = "checked" } : null) @((OrderStatus)item)
                    isChecked = false;
                }
            </td>
            <td>@Html.ValidationMessageFor(m => m.order_status_id)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.customer_id)</td>
            <td>
                @Html.DropDownListFor(m => m.customer_id, ViewBag.CustomerData as List<SelectListItem>, "Select Customer", null)
            </td>
            <td>@Html.ValidationMessageFor(m => m.customer_id)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.capacity)</td>
            <td>
                @Html.TextBoxFor(m => m.capacity)
            </td>
            <td>@Html.ValidationMessageFor(m => m.capacity)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.estimated_capacity)</td>
            <td>
                @Html.TextBoxFor(m => m.estimated_capacity)
            </td>
            <td>@Html.ValidationMessageFor(m => m.estimated_capacity)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.delivery_address)</td>
            <td>
                @Html.TextAreaFor(m => m.delivery_address, new { row = 5, cols = 20 })
            </td>
            <td>@Html.ValidationMessageFor(m => m.delivery_address)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.service_total_price)</td>
            <td>
                @Html.TextBoxFor(m => m.service_total_price)
            </td>
            <td>@Html.ValidationMessageFor(m => m.service_total_price)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.priority)</td>
            <td>
                @Html.TextBoxFor(m => m.priority)
            </td>
            <td>@Html.ValidationMessageFor(m => m.priority)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.review_id)</td>
            <td>
                @Html.TextBoxFor(m => m.review_id)
            </td>
            <td>@Html.ValidationMessageFor(m => m.review_id)</td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Create" /></td>
        </tr>
    </table>
}

LuandryCustomerApp/Views/PlacedOrders/Delete.cshtml
@model LuandryCustomerApp.placed_orders


<h2>Delete Orders</h2>
@using (Html.BeginForm("delete", "PlacedOrders", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.id)
    <div class="form-group">
        <label>Create At</label>
        <p>@Model.created_at</p>
    </div>
    <div class="form-group">
        <label>Update At</label>
        <p>@Model.updated_at</p>
    </div>
    <div class="form-group">
        <label>Delete At</label>
        <p>@Model.deleted_at</p>
    </div>
    <div class="form-group">
        <label>Store Id</label>
        <p>@Model.store_id</p>
    </div>
    <div class="form-group">
        <label>Time Placed</label>
        <p>@Model.time_placed</p>
    </div>
    <div class="form-group">
        <label>Detail</label>
        <p>@Model.detail</p>
    </div>
    <div class="form-group">
        <label>Status</label>
        <p>@Model.order_status_id</p>
    </div>
    <div class="form-group">
        <label>Customer Id</label>
        <p>@Model.customer_id</p>
    </div>
    <div class="form-group">
        <label>Capacity</label>
        <p>@Model.capacity</p>
    </div>
    <div class="form-group">
        <label>Estimated Capacity</label>
        <p>@Model.estimated_capacity</p>
    </div>
    <div class="form-group">
        <label>Delivery Address</label>
        <p>@Model.delivery_address</p>
    </div>
    <div class="form-group">
        <label>Delivery Latitude</label>
        <p>@Model.delivery_latitude</p>
    </div>
    <div class="form-group">
        <label>Delivery Longitude</label>
        <p>@Model.delivery_longitude</p>
    </div>
    <div class="form-group">
        <label>Total Price</label>
        <p>@Model.service_total_price</p>
    </div>
    <div class="form-group">
        <label>Priority</label>
        <p>@Model.priority</p>
    </div>
    <div class="form-group">
        <label>Review Id</label>
        <p>@Model.review_id</p>
    </div>
    <div><input type="submit" value="Delete" /></div>
    

}

LuandryCustomerApp/Views/PlacedOrders/Edit.cshtml
@model PlacedOrderModifyViewModel
@{
    ViewBag.Title = "Edit";
}

<style>
    .field-validation-error {
        color: red;
    }

    .field-validation-error {
        border-color: red;
    }
</style>


@using (Html.BeginForm("Edit", "PlacedOrders", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <table>
        <td colspan="3">@Html.HiddenFor(m => m.id)</td>
        <tr>
                <td>@Html.DisplayNameFor(m => m.store_id)</td>
                <td>
                    @Html.DropDownListFor(m => m.store_id, ViewBag.StoreData as List<SelectListItem>, "Select Store", null)
                </td>
                <td>@Html.ValidationMessageFor(m => m.store_id)</td>

        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.time_placed)</td>
            <td>
                @Html.TextBoxFor(m => m.time_placed)
            </td>
            <td>@Html.ValidationMessageFor(m => m.time_placed)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.detail)</td>
            <td>
                @Html.TextBoxFor(m => m.detail)
            </td>
            <td>@Html.ValidationMessageFor(m => m.detail)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.order_status_id)</td>
            <td>

                @foreach (var item in (int[])Enum.GetValues(typeof(OrderStatus)))
                {
                    @Html.RadioButtonFor(m => m.order_status_id, item, (OrderStatus)item == Model.order_status_id ? new { @checked = "checked" } : null) @((OrderStatus)item)
                }
            </td>
            <td>@Html.ValidationMessageFor(m => m.order_status_id)</td>
        </tr>
        <tr>
                <td>@Html.DisplayNameFor(m => m.customer_id)</td>
                <td>
                    @Html.DropDownListFor(m => m.customer_id, ViewBag.CustomerData as List<SelectListItem>, "Select Customer", null)
                </td>
                <td>@Html.ValidationMessageFor(m => m.customer_id)</td>
            </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.capacity)</td>
            <td>
                @Html.TextBoxFor(m => m.capacity)
            </td>
            <td>@Html.ValidationMessageFor(m => m.capacity)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.estimated_capacity)</td>
            <td>
                @Html.TextBoxFor(m => m.estimated_capacity)
            </td>
            <td>@Html.ValidationMessageFor(m => m.estimated_capacity)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.delivery_address)</td>
            <td>
                @Html.TextAreaFor(m => m.delivery_address, new { row = 5, cols = 20 })
            </td>
            <td>@Html.ValidationMessageFor(m => m.delivery_address)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.service_total_price)</td>
            <td>
                @Html.TextBoxFor(m => m.service_total_price)
            </td>
            <td>@Html.ValidationMessageFor(m => m.service_total_price)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.priority)</td>
            <td>
                @Html.TextBoxFor(m => m.priority)
            </td>
            <td>@Html.ValidationMessageFor(m => m.priority)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(m => m.review_id)</td>
            <td>
                @Html.TextBoxFor(m => m.review_id)
            </td>
            <td>@Html.ValidationMessageFor(m => m.review_id)</td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Save" /></td>
        </tr>
    </table>
}

LuandryCustomerApp/Views/PlacedOrders/Index.cshtml
@model IEnumerable<PlacedOrderListViewModel>
@{
    ViewBag.Title = "PlacedOrder Management";

    var routeValues = new RouteValueDictionary()
    {
        ["PageNumber"] = ViewBag.PageNumber,
        ["PageSize"] = ViewBag.PageSize,
        ["SortField"] = ViewBag.SortField,
    };
    int count = Model.Count();
    var defaultQueryString = Html.BuildQueryString(routeValues);
}

<!-- extra div for emulating position:fixed of the menu -->
<div class="st-content-inner">
    <div class="container-fluid">

        <div class="page-section">
            <div class="row">
                <div class="col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
                    <h4 class="page-section-heading">Placed Orders Infomation</h4>
                    <div class="panel panel-default">

                        <div class="mb-10 col-md-4 col-sm-6 col-lg-3">
                            @{
                                routeValues["PageNumber"] = 1;
                                routeValues["SortField"] = ViewBag.SortField;
                                Html.RenderPartial("ListViewComponents/_PageSize", new PageSizeViewModel()
                                {
                                    SelectedValue = ViewBag.PageSize,
                                    RouteValues = routeValues
                                });
                            }
                            <i style="color:#3498DB" class="md md-add-box"></i><a href="/PlacedOrders/Create">Create Customer</a>
                        </div>
                        @*<div class="mb-10">
                            @{
                                routeValues["PageNumber"] = 1;
                                routeValues["PageSize"] = ViewBag.PageSize;
                                routeValues["SortField"] = ViewBag.SortField;
                                using (Html.BeginForm("Index", "PlacedOrders", routeValues, FormMethod.Post, null))
                                {
                                }
                            }
                        </div>*@
                        <!-- Data table -->
                        <table class="table" cellspacing="0" width="100%" id="table1">
                            <thead>
                                <tr>
                                    @{
                                        routeValues["PageNumber"] = 1;
                                        routeValues["PageSize"] = ViewBag.PageSize;
                                    }
                                    <th>@Html.BuildSortFieldFor(m => m.id, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.created_at, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.updated_at, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    @*<th>@Html.BuildSortFieldFor(m => m.deleted_at, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>*@
                                    <th>@Html.BuildSortFieldFor(m => m.store_id, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.time_placed, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.detail, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.order_status_id, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.customer_id, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.capacity, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.estimated_capacity, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.delivery_address, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    @*<th>@Html.BuildSortFieldFor(m => m.delivery_latitude, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>*@
                                    @*<th>@Html.BuildSortFieldFor(m => m.delivery_longitude, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>*@
                                    <th>@Html.BuildSortFieldFor(m => m.service_total_price, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.priority, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th>@Html.BuildSortFieldFor(m => m.review_id, ViewBag.SortField as string, "Index", "PlacedOrders", routeValues, null)</th>
                                    <th style="color:#3498DB">Delete</th>
                                    @*<th style="color:#3498DB">Delete</th>*@
                                </tr>
                            </thead>
                            
                            <tbody id="tbody1" data-routeValues="@defaultQueryString" data-numberOfRows="@count">
                                @foreach (var item in Model)
                                {
                                <tr>
                                    @*<td>@Html.DisplayFor(m => item.id)</td>*@
                                    <td>@Html.ActionLink("Edit","Edit", "PlacedOrders", new { id = item.id }, null)</td>
                                    <td>@Html.DisplayFor(m => item.created_at)</td>
                                    <td>@Html.DisplayFor(m => item.updated_at)</td>
                                    @*<td>@Html.DisplayFor(m => item.deleted_at)</td>*@
                                    <td>@Html.DisplayFor(m => item.store_id)</td>
                                    <td>@Html.DisplayFor(m => item.time_placed)</td>
                                    <td>@Html.DisplayFor(m => item.detail)</td>
                                    <td>@Html.DisplayFor(m => item.order_status_id)</td>
                                    <td>@Html.DisplayFor(m => item.customer_id)</td>
                                    <td>@Html.DisplayFor(m => item.capacity)</td>
                                    <td>@Html.DisplayFor(m => item.estimated_capacity)</td>
                                    <td>@Html.DisplayFor(m => item.delivery_address)</td>
                                    @*<td>@Html.DisplayFor(m => item.delivery_latitude)</td>*@
                                    @*<td>@Html.DisplayFor(m => item.delivery_longitude)</td>*@
                                    <td>@Html.DisplayFor(m => item.service_total_price)</td>
                                    <td>@Html.DisplayFor(m => item.priority)</td>
                                    <td>@Html.DisplayFor(m => item.review_id)</td>
                                    <td>
                                        @using (Html.BeginForm("Delete", "PlacedOrders", FormMethod.Post))
                                        {
                                            @Html.Hidden("RouteValues", Html.CombineQueryString(defaultQueryString, new Dictionary<string, object>() { ["NumberOfRows"] = count }))
                                            @Html.Hidden("Id", item.id)
                                            <input class="btn btn-danger" type="submit" value="Delete" />
                                        }
                                    </td>
                                    @*<td>
            <input type="button" value="Delete By Ajax" data-deleteId="@item.id" />
        </td>*@
                                </tr>
                                }
                            </tbody>
                        </table>

                        <div class="mb-10">
                            @{
                                routeValues["PageSize"] = ViewBag.PageSize;
                                routeValues["SortField"] = ViewBag.SortField;
                                Html.RenderAction("RenderPaging", "ListViewComponents", new
                                {
                                    pagingViewModel = new PagingViewModel()
                                    {
                                        Action = "Index",
                                        Controller = "PlacedOrders",
                                        PageNumber = ViewBag.PageNumber,
                                        TotalPages = ViewBag.TotalPages,
                                        RouteValues = routeValues
                                    }
                                });
                            }
                        </div>


                        <!-- // Data table -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /st-content-inner -->




@section CustomJs{
    <script type="text/javascript">

        document.addEventListener('DOMContentLoaded', function () {
            var $pageSize = document.getElementById('pageSize');

            //event
            $pageSize.addEventListener('change', function () {
                var routeValues = this.getAttribute('data-routeValues');

                var url = `/PlacedOrders/Index?pagesize=${this.value}`;
                url += routeValues !== '' ? `&${routeValues}` : '';
                window.location = url;
            });


            /*----------------------------------*/
            var $table1 = document.getElementById('table1');
            var $tbody1 = $table1.tBodies.namedItem('tbody1');

            $tbody1.addEventListener('click', function (event) {
                event = event || window.event;
                event.target = event.target || event.srcElement;

                var $target = event.target;
                if ($target.type === 'button' && $target.hasAttribute('data-deleteId')) {
                    var id = $target.getAttribute('data-deleteId'),
                        routeValues = $tbody1.getAttribute('data-routeValues'),
                        numberOfRows = $tbody1.getAttribute('data-numberOfRows');

                    var client = new XMLHttpRequest();
                    client.onreadystatechange = function () {
                        if (this.readyState == 4) {
                            switch (this.status) {
                                case 200: {
                                    alert(this.statusText);

                                    var pattern = /pagenumber=(\d+)/i;
                                    if (numberOfRows == 1) {
                                        if (pattern.test(routeValues)) {
                                            var pageNumber = routeValues.match(pattern)[1];

                                            if (pageNumber > 1) {
                                                routeValues = routeValues.replace(pattern, `PageNumber=${(pageNumber - 1)}`);
                                            }
                                        }
                                    }

                                    window.location = '/PlacedOrders/Index' + (routeValues !== '' ? `?${routeValues}` : '');
                                    break;
                                }

                                case 400: break;

                                case 404: break;

                                case 500: break;
                                default: break;
                            }
                        }
                    }

                    client.open('post', '/PlacedOrders/Delete', true);
                    client.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
                    client.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                    client.send(`id=${id}`);

                }
            });
        })
    </script>
}